/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as StreamCreateRouteImport } from './routes/stream/create'
import { Route as StreamViewIdRouteImport } from './routes/stream/view/$id'
import { Route as StreamBroadcastIdRouteImport } from './routes/stream/broadcast/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamCreateRoute = StreamCreateRouteImport.update({
  id: '/stream/create',
  path: '/stream/create',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamViewIdRoute = StreamViewIdRouteImport.update({
  id: '/stream/view/$id',
  path: '/stream/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamBroadcastIdRoute = StreamBroadcastIdRouteImport.update({
  id: '/stream/broadcast/$id',
  path: '/stream/broadcast/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stream/create': typeof StreamCreateRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/stream/broadcast/$id': typeof StreamBroadcastIdRoute
  '/stream/view/$id': typeof StreamViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stream/create': typeof StreamCreateRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/stream/broadcast/$id': typeof StreamBroadcastIdRoute
  '/stream/view/$id': typeof StreamViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stream/create': typeof StreamCreateRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/stream/broadcast/$id': typeof StreamBroadcastIdRoute
  '/stream/view/$id': typeof StreamViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stream/create'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/stream/broadcast/$id'
    | '/stream/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stream/create'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/stream/broadcast/$id'
    | '/stream/view/$id'
  id:
    | '__root__'
    | '/'
    | '/stream/create'
    | '/auth/'
    | '/dashboard/'
    | '/profile/'
    | '/stream/broadcast/$id'
    | '/stream/view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StreamCreateRoute: typeof StreamCreateRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  StreamBroadcastIdRoute: typeof StreamBroadcastIdRoute
  StreamViewIdRoute: typeof StreamViewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/create': {
      id: '/stream/create'
      path: '/stream/create'
      fullPath: '/stream/create'
      preLoaderRoute: typeof StreamCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/view/$id': {
      id: '/stream/view/$id'
      path: '/stream/view/$id'
      fullPath: '/stream/view/$id'
      preLoaderRoute: typeof StreamViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/broadcast/$id': {
      id: '/stream/broadcast/$id'
      path: '/stream/broadcast/$id'
      fullPath: '/stream/broadcast/$id'
      preLoaderRoute: typeof StreamBroadcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StreamCreateRoute: StreamCreateRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  StreamBroadcastIdRoute: StreamBroadcastIdRoute,
  StreamViewIdRoute: StreamViewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
